steps:
  - name: "gcr.io/cloud-builders/docker"
    env:
      - "DBHOST=$DBHOST"
      - "DBUSER=$DBUSER"
      - "DBPASSWORD=$DBPASSWORD"
      - "DBPORT=$DBPORT"
      - "DBNAME=$DBNAME"
      - "JWT_SECRET=$JWT_SECRET"
    args:
      - "build"
      - "."
      - "--tag"
      - "atc2160/comsw4153-cloud-composite-service:v17"
      - "--build-arg"
      - "DBHOST=$DBHOST"
      - "--build-arg"
      - "DBUSER=$DBUSER"
      - "--build-arg"
      - "DBPASSWORD=$DBPASSWORD"
      - "--build-arg"
      - "DBPORT=$DBPORT"
      - "--build-arg"
      - "DBNAME=$DBNAME"
      - "--build-arg"
      - "JWT_SECRET=$JWT_SECRET"
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "atc2160/comsw4153-cloud-composite-service:v17"

availableSecrets:
  secretManager:
    - versionName: "projects/norse-bond-439820-h5/secrets/DBHOST/versions/latest"
      env: "DBHOST"
    - versionName: "projects/norse-bond-439820-h5/secrets/DBUSER/versions/latest"
      env: "DBUSER"
    - versionName: "projects/norse-bond-439820-h5/secrets/DBPASSWORD/versions/latest"
      env: "DBPASSWORD"
    - versionName: "projects/norse-bond-439820-h5/secrets/DBPORT/versions/latest"
      env: "DBPORT"
    - versionName: "projects/norse-bond-439820-h5/secrets/DBNAME/versions/latest"
      env: "DBNAME"
    - versionName: "projects/norse-bond-439820-h5/secrets/JWT_SECRET/versions/latest"
      env: "JWT_SECRET"
